### PR TITLE
Add question about 'release' version report

### PR DESCRIPTION
**Pull request by mattharris**

### CODE REVIEW

**Comment by bobjacobsen** [comment]
This PR adds a question about how the "by date" releases that we refer (new) users to refer to themselves, and whether they're identical.

My thinking was that they would be the _identical_ tag, hence same SHA, but the build process would change the name that the Version class (hence startup screen) uses, and the filename.  With the rebuild of the installers to include the year-specific name, the installers checksums would be different, but the JMRI content (checked out SHA) would be the same.

**Comment by mattharris** [comment]
OK, that is clear. So `jmri.Version.name()` would return `2020-07-21.4.2` for the release version, whereas the associated rolling-release version `jmri.Version.name()` would return `21.4.2` (assuming the version numbers used in previous examples). The two are, otherwise, identical.

**Comment by bobjacobsen** [comment]
Perhaps we can explain it like this, using a SHA from the top of the dev-minor branch as an example:

 - a developer build on their local machine:  4.24.0ish-jake-20200625T1452Z-R7da91146e0 (same as now, with next number on that branch; want to replace "ish" with something lord ambiguous? i.e. "predecessor"?)
 - Jenkins installer builds:  4.24.0ish-20200625T1452Z-R7da91146e0 (just remove name of who built it; we could replace the with i.e. 'Jenkins' instead)
 - release build that's made available as installers on main web site, has release note, etc: 4.24.0-20200625T1452Z-R7da91146e0
 - _recommended_ installer files, in some sense a replacement for what we currently call a "production release" - is 2020-11-4.24.0-20200625T1452Z-R7da91146e0. (but we can shorten that by leaving off the last one two or even three groups without ambiguity)

All of those represent the same underlying Git content and have the same SHA.  They were built with different versions strings embedded in the installers and different installer file names.

**Comment by mattharris** [comment]
How about (using SHA 7da91146e0 as example):

* developer build on local machine: 4.24.0private-jake-20200625T1452Z-R7da91146e0 (using `private` to denote a private build)
* Jenkins installer builds: 4.24.0ish-20200625T1452Z-R7da91146e0 <- no tag
* release build: 4.24.0-20200625T1452Z-R7da91146e0 <- tagged as `v4.24.0`
* _recommended_ installer: 2020-11-4.24.0 <- tagged as `v2020-11` (or, perhaps, `r2020-11` for 'release 2020-11' as this could help with certain build pipeline automation)

The value in having the commit SHA for the _recommended_ _version_ is, perhaps, minimal as we already **know** from the fact that it's the `2020-11` _recommended_ _version_ and, thereby, can grab from appropriate tag.

While calling it `2020-11` has a certain appeal, I _think_ that still incorporating the semantic version number (a.k.a the `4.24.0`) has value as we would still be reporting this via `jmri.Version`.

So, a _recommended_ _version_ would have:

* `jmri.Version.major = 4`
* `jmri.Version.minor = 20`
* `jmri.Version.test = 0`
* `jmri.Version.name() = 2020-11-4.20.0`

This will need some minor changes to `jmri.Version` and the build scripts to handle, but I feel separates out the different use cases and makes thing clearer.

Does this make sense?

**Comment by bobjacobsen** [comment]
Thanks for working that out in detail.  Can I make two friendly amendments?  
 - Add a dash in 4.24.0private-jake-20200625T1452Z-R7da91146e0 so that it's 4.24.0-private-jake-20200625T1452Z-R7da91146e0
 - change the "ish" on Jenkins builds to some like i.e. 4.24.0-dev-Jenkins-20200625T1452Z-R7da91146e0 That way we can still refer to "deveiopment builds", but this time with a referent.

I agree on 2020-11-4.20.0 although IIRC there was a suggestion of 2020-Oct-4.20.0 or even 2020-October-4.20.0. I don't feel strongly about that.

I think `r2020-11` is better than `v2020-11` as it's really clear what kind of thing it's referring to.

If you update your branch I'd be happy to merge it.

**Comment by mattharris** [comment]
I've incorporated most of these comments.

I've kept with the `+R` convention for the Git SHA hash naming as today as that is more an artefact of the build process and fits with what we've been doing pretty much since the switch to Git.

I didn't add anything about how `jmri.Version` should behave - do you think that is necessary here?

**Comment by bobjacobsen** [comment]
Thank you!

I'm not sure I understand Version.java, release.properties, Jenkins environment, etc enough to really comment on it.  I think that can wait until after we implement whatever is worked out here.

**Pull request merged**
